name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python.3.6.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.11
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov gym flask msgpack
      - name: Unit tests
        run: |
          ./scripts/test
